// GENERATED by scripts/generate-data.mjs — do not edit by hand.
// Source: node-areacodes data.json (MIT). NANP area code -> primary city/state
// plus a representative coordinate used for "use my location".
export interface AreaCodeInfo {
  code: string;
  city: string;
  state: string;
  lat?: number;
  lng?: number;
}

export const AREA_CODES: readonly AreaCodeInfo[] = [
  {
    "code": "201",
    "city": "Bayonne",
    "state": "NJ",
    "lat": 40.925692,
    "lng": -74.073135
  },
  {
    "code": "202",
    "city": "Washington",
    "state": "DC",
    "lat": 38.904789,
    "lng": -77.016273
  },
  {
    "code": "203",
    "city": "Bridgeport",
    "state": "CT",
    "lat": 41.341175,
    "lng": -73.167001
  },
  {
    "code": "205",
    "city": "Birmingham",
    "state": "AL",
    "lat": 33.369918,
    "lng": -87.418475
  },
  {
    "code": "206",
    "city": "Seattle",
    "state": "WA",
    "lat": 47.56621,
    "lng": -122.395643
  },
  {
    "code": "207",
    "city": "Portland",
    "state": "ME",
    "lat": 45.30897,
    "lng": -69.1782
  },
  {
    "code": "208",
    "city": "Boise",
    "state": "ID",
    "lat": 44.38906,
    "lng": -114.659367
  },
  {
    "code": "209",
    "city": "Lodi",
    "state": "CA",
    "lat": 37.810234,
    "lng": -120.524619
  },
  {
    "code": "210",
    "city": "San Antonio",
    "state": "TX",
    "lat": 29.446946,
    "lng": -98.502244
  },
  {
    "code": "212",
    "city": "New York City",
    "state": "NY",
    "lat": 40.781428,
    "lng": -73.965434
  },
  {
    "code": "213",
    "city": "Los Angeles",
    "state": "CA",
    "lat": 34.049442,
    "lng": -118.266392
  },
  {
    "code": "214",
    "city": "Dallas",
    "state": "TX",
    "lat": 32.771888,
    "lng": -96.647071
  },
  {
    "code": "215",
    "city": "Levittown",
    "state": "PA",
    "lat": 40.241084,
    "lng": -75.15556
  },
  {
    "code": "216",
    "city": "Cleveland",
    "state": "OH",
    "lat": 41.466283,
    "lng": -81.630237
  },
  {
    "code": "217",
    "city": "Champaign",
    "state": "IL",
    "lat": 39.787445,
    "lng": -89.339116
  },
  {
    "code": "218",
    "city": "Duluth",
    "state": "MN",
    "lat": 47.617058,
    "lng": -94.077273
  },
  {
    "code": "219",
    "city": "Gary",
    "state": "IN",
    "lat": 41.167422,
    "lng": -86.10073
  },
  {
    "code": "220",
    "city": "Athens",
    "state": "OH",
    "lat": 39.68925,
    "lng": -82.238329
  },
  {
    "code": "223",
    "city": "Lancaster",
    "state": "PA",
    "lat": 40.155116,
    "lng": -77.060091
  },
  {
    "code": "224",
    "city": "Arlington Heights",
    "state": "IL",
    "lat": 42.195629,
    "lng": -88.103663
  },
  {
    "code": "225",
    "city": "Baton Rouge",
    "state": "LA",
    "lat": 30.529115,
    "lng": -91.114891
  },
  {
    "code": "227",
    "city": "Silver Spring",
    "state": "MD",
    "lat": 38.990665,
    "lng": -77.026088
  },
  {
    "code": "228",
    "city": "Biloxi",
    "state": "MS",
    "lat": 30.498325,
    "lng": -88.990244
  },
  {
    "code": "229",
    "city": "Albany",
    "state": "GA",
    "lat": 31.473049,
    "lng": -84.033645
  },
  {
    "code": "231",
    "city": "Grant",
    "state": "MI",
    "lat": 44.567455,
    "lng": -85.470799
  },
  {
    "code": "234",
    "city": "Akron",
    "state": "OH",
    "lat": 40.909482,
    "lng": -81.309358
  },
  {
    "code": "239",
    "city": "Cape Coral",
    "state": "FL",
    "lat": 26.069419,
    "lng": -81.419083
  },
  {
    "code": "240",
    "city": "Aspen Hill",
    "state": "MD",
    "lat": 39.077466,
    "lng": -77.839196
  },
  {
    "code": "248",
    "city": "Farmington Hills",
    "state": "MI",
    "lat": 42.644892,
    "lng": -83.401584
  },
  {
    "code": "251",
    "city": "Mobile",
    "state": "AL",
    "lat": 31.216421,
    "lng": -87.652638
  },
  {
    "code": "252",
    "city": "Elizabeth City",
    "state": "NC",
    "lat": 35.685581,
    "lng": -76.934414
  },
  {
    "code": "253",
    "city": "Kent",
    "state": "WA",
    "lat": 47.215973,
    "lng": -122.433656
  },
  {
    "code": "254",
    "city": "Eastland",
    "state": "TX",
    "lat": 31.764308,
    "lng": -97.710172
  },
  {
    "code": "256",
    "city": "Decatur",
    "state": "AL",
    "lat": 34.148987,
    "lng": -86.452873
  },
  {
    "code": "260",
    "city": "Fort Wayne",
    "state": "IN",
    "lat": 41.093442,
    "lng": -85.241781
  },
  {
    "code": "262",
    "city": "Kenosha",
    "state": "WI",
    "lat": 42.950573,
    "lng": -88.283516
  },
  {
    "code": "267",
    "city": "Levittown",
    "state": "PA",
    "lat": 40.241084,
    "lng": -75.15556
  },
  {
    "code": "269",
    "city": "Allegan",
    "state": "MI",
    "lat": 42.211698,
    "lng": -85.741985
  },
  {
    "code": "270",
    "city": "Bowling Green",
    "state": "KY",
    "lat": 37.105285,
    "lng": -88.166884
  },
  {
    "code": "272",
    "city": "Back Mountain",
    "state": "PA",
    "lat": 41.329586,
    "lng": -76.0678680461039
  },
  {
    "code": "274",
    "city": "Green Bay",
    "state": "WI",
    "lat": 44.519158,
    "lng": -88.019826
  },
  {
    "code": "276",
    "city": "Danville",
    "state": "VA",
    "lat": 36.87419,
    "lng": -81.622088
  },
  {
    "code": "278",
    "city": "ann arbor",
    "state": "MI",
    "lat": 42.280825,
    "lng": -83.743037
  },
  {
    "code": "279",
    "city": "Arden-Arcade",
    "state": "CA",
    "lat": 38.6039613,
    "lng": -121.383003529994
  },
  {
    "code": "281",
    "city": "Baytown",
    "state": "TX",
    "lat": 29.837525,
    "lng": -95.377346
  },
  {
    "code": "283",
    "city": "Cincinnati",
    "state": "OH",
    "lat": 39.103118,
    "lng": -84.512019
  },
  {
    "code": "301",
    "city": "Aspen Hill",
    "state": "MD",
    "lat": 39.077466,
    "lng": -77.839196
  },
  {
    "code": "302",
    "city": "Dover",
    "state": "DE",
    "lat": 39.073022,
    "lng": -75.462006
  },
  {
    "code": "303",
    "city": "Aurora",
    "state": "CO",
    "lat": 39.713461,
    "lng": -104.82857
  },
  {
    "code": "304",
    "city": "Charleston",
    "state": "WV",
    "lat": 38.642574,
    "lng": -80.61372
  },
  {
    "code": "305",
    "city": "Miami",
    "state": "FL",
    "lat": 25.300831,
    "lng": -80.856754
  },
  {
    "code": "307",
    "city": "Casper",
    "state": "WY",
    "lat": 42.999627,
    "lng": -107.551447
  },
  {
    "code": "308",
    "city": "Kearney",
    "state": "NE",
    "lat": 41.454586,
    "lng": -101.145726
  },
  {
    "code": "309",
    "city": "Bloomington",
    "state": "IL",
    "lat": 40.802537,
    "lng": -89.95696
  },
  {
    "code": "310",
    "city": "Los Angeles",
    "state": "CA",
    "lat": 33.515574,
    "lng": -118.777633
  },
  {
    "code": "312",
    "city": "Chicago",
    "state": "IL",
    "lat": 41.873277,
    "lng": -87.645204
  },
  {
    "code": "313",
    "city": "Dearborn",
    "state": "MI",
    "lat": 42.345428,
    "lng": -83.146191
  },
  {
    "code": "314",
    "city": "Florissant",
    "state": "MO",
    "lat": 38.67023,
    "lng": -90.337973
  },
  {
    "code": "315",
    "city": "Syracuse",
    "state": "NY",
    "lat": 43.557021,
    "lng": -75.737581
  },
  {
    "code": "316",
    "city": "Wichita",
    "state": "KS",
    "lat": 37.75168,
    "lng": -97.247515
  },
  {
    "code": "317",
    "city": "Indianapolis",
    "state": "IN",
    "lat": 39.766543,
    "lng": -86.128131
  },
  {
    "code": "318",
    "city": "Bossier City",
    "state": "LA",
    "lat": 32.062174,
    "lng": -92.544682
  },
  {
    "code": "319",
    "city": "Cedar Rapids",
    "state": "IA",
    "lat": 42.107799,
    "lng": -91.562776
  },
  {
    "code": "320",
    "city": "Alexandria",
    "state": "MN",
    "lat": 45.52735,
    "lng": -94.793149
  },
  {
    "code": "321",
    "city": "Melbourne",
    "state": "FL",
    "lat": 28.303802,
    "lng": -81.066529
  },
  {
    "code": "323",
    "city": "Los Angeles",
    "state": "CA",
    "lat": 34.037423,
    "lng": -118.254201
  },
  {
    "code": "325",
    "city": "Abilene",
    "state": "TX",
    "lat": 31.544876,
    "lng": -100.102418
  },
  {
    "code": "326",
    "city": "Dayton",
    "state": "OH",
    "lat": 39.737478,
    "lng": -83.943091
  },
  {
    "code": "327",
    "city": "Jonesboro",
    "state": "AR",
    "lat": 34.729392,
    "lng": -92.083437
  },
  {
    "code": "330",
    "city": "Akron",
    "state": "OH",
    "lat": 40.909482,
    "lng": -81.309358
  },
  {
    "code": "331",
    "city": "Aurora",
    "state": "IL",
    "lat": 41.810713,
    "lng": -88.254341
  },
  {
    "code": "332",
    "city": "Manhattan",
    "state": "NY",
    "lat": 40.7900869,
    "lng": -73.9598295
  },
  {
    "code": "334",
    "city": "Auburn",
    "state": "AL",
    "lat": 31.748015,
    "lng": -86.710752
  },
  {
    "code": "336",
    "city": "Greensboro",
    "state": "NC",
    "lat": 36.165262,
    "lng": -80.203652
  },
  {
    "code": "337",
    "city": "Lafayette",
    "state": "LA",
    "lat": 30.363876,
    "lng": -92.68289
  },
  {
    "code": "339",
    "city": "Lynn",
    "state": "MA",
    "lat": 42.255792,
    "lng": -70.993819
  },
  {
    "code": "340",
    "city": "charlotte amalie",
    "state": "VI",
    "lat": 18.3419,
    "lng": -64.9307
  },
  {
    "code": "341",
    "city": "Oakland",
    "state": "CA",
    "lat": 37.804363,
    "lng": -122.271113
  },
  {
    "code": "346",
    "city": "Alvin",
    "state": "TX",
    "lat": 29.4238472,
    "lng": -95.2441009
  },
  {
    "code": "347",
    "city": "Bronx",
    "state": "NY",
    "lat": 40.685997,
    "lng": -73.935788
  },
  {
    "code": "351",
    "city": "Haverhill",
    "state": "MA",
    "lat": 42.587448,
    "lng": -71.595462
  },
  {
    "code": "352",
    "city": "Gainesville",
    "state": "FL",
    "lat": 29.166672,
    "lng": -82.335163
  },
  {
    "code": "360",
    "city": "Bellingham",
    "state": "WA",
    "lat": 47.453869,
    "lng": -122.407745
  },
  {
    "code": "361",
    "city": "Corpus Christi",
    "state": "TX",
    "lat": 28.075417,
    "lng": -97.67658
  },
  {
    "code": "364",
    "city": "Owensboro",
    "state": "KY",
    "lat": 37.105285,
    "lng": -88.166884
  },
  {
    "code": "369",
    "city": "santa rosa",
    "state": "CA",
    "lat": 38.440429,
    "lng": -122.714054
  },
  {
    "code": "380",
    "city": "Columbus",
    "state": "OH",
    "lat": 39.961175,
    "lng": -82.998794
  },
  {
    "code": "385",
    "city": "Ogden",
    "state": "UT",
    "lat": 40.617162,
    "lng": -111.805673
  },
  {
    "code": "386",
    "city": "Daytona Beach",
    "state": "FL",
    "lat": 29.755314,
    "lng": -82.175609
  },
  {
    "code": "401",
    "city": "Cranston",
    "state": "RI",
    "lat": 41.604967,
    "lng": -71.5344
  },
  {
    "code": "402",
    "city": "Columbus",
    "state": "NE",
    "lat": 41.623995,
    "lng": -98.025861
  },
  {
    "code": "404",
    "city": "Atlanta",
    "state": "GA",
    "lat": 33.739497,
    "lng": -84.392472
  },
  {
    "code": "405",
    "city": "Midwest City",
    "state": "OK",
    "lat": 35.390576,
    "lng": -97.472448
  },
  {
    "code": "406",
    "city": "Billings",
    "state": "MT",
    "lat": 47.033533,
    "lng": -109.64515
  },
  {
    "code": "407",
    "city": "Altamonte Springs",
    "state": "FL",
    "lat": 28.325064,
    "lng": -81.22196
  },
  {
    "code": "408",
    "city": "Gilroy",
    "state": "CA",
    "lat": 37.227493,
    "lng": -121.70066
  },
  {
    "code": "409",
    "city": "Beaumont",
    "state": "TX",
    "lat": 30.323281,
    "lng": -94.291657
  },
  {
    "code": "410",
    "city": "Annapolis",
    "state": "MD",
    "lat": 38.896232,
    "lng": -76.110627
  },
  {
    "code": "412",
    "city": "Pittsburgh",
    "state": "PA",
    "lat": 40.432942,
    "lng": -79.975833
  },
  {
    "code": "413",
    "city": "Chicopee",
    "state": "MA",
    "lat": 42.352791,
    "lng": -72.831601
  },
  {
    "code": "414",
    "city": "Milwaukee",
    "state": "WI",
    "lat": 42.996968,
    "lng": -87.976898
  },
  {
    "code": "415",
    "city": "San Francisco",
    "state": "CA",
    "lat": 37.986719,
    "lng": -122.679559
  },
  {
    "code": "417",
    "city": "Springfield",
    "state": "MO",
    "lat": 37.216256,
    "lng": -93.181131
  },
  {
    "code": "419",
    "city": "Toledo",
    "state": "OH",
    "lat": 40.998598,
    "lng": -83.55333
  },
  {
    "code": "423",
    "city": "Chattanooga",
    "state": "TN",
    "lat": 35.883792,
    "lng": -83.924438
  },
  {
    "code": "424",
    "city": "Beverly Hills",
    "state": "CA",
    "lat": 33.515574,
    "lng": -118.777633
  },
  {
    "code": "425",
    "city": "Bellevue",
    "state": "WA",
    "lat": 47.570178,
    "lng": -121.886616
  },
  {
    "code": "430",
    "city": "Longview",
    "state": "TX",
    "lat": 32.705051,
    "lng": -95.389774
  },
  {
    "code": "432",
    "city": "Midland",
    "state": "TX",
    "lat": 30.879595,
    "lng": -102.924163
  },
  {
    "code": "434",
    "city": "Lynchburg",
    "state": "VA",
    "lat": 37.184108,
    "lng": -78.597018
  },
  {
    "code": "435",
    "city": "Cedar City",
    "state": "UT",
    "lat": 39.306817,
    "lng": -111.718184
  },
  {
    "code": "440",
    "city": "Cleveland",
    "state": "OH",
    "lat": 41.483337,
    "lng": -81.422584
  },
  {
    "code": "442",
    "city": "Apple Valley",
    "state": "CA",
    "lat": 34.500831,
    "lng": -117.185875
  },
  {
    "code": "443",
    "city": "Baltimore",
    "state": "MD",
    "lat": 38.896232,
    "lng": -76.110627
  },
  {
    "code": "445",
    "city": "Philadelphia",
    "state": "PA",
    "lat": 40.241084,
    "lng": -75.15556
  },
  {
    "code": "447",
    "city": "Champaign",
    "state": "IL",
    "lat": 40.11642,
    "lng": -88.243382
  },
  {
    "code": "458",
    "city": "Eugene",
    "state": "OR",
    "lat": 44.052069,
    "lng": -123.086753
  },
  {
    "code": "463",
    "city": "Carmel",
    "state": "IN",
    "lat": 39.9788383,
    "lng": -86.118731
  },
  {
    "code": "464",
    "city": "Cicero",
    "state": "IL",
    "lat": 41.845587,
    "lng": -87.753944
  },
  {
    "code": "469",
    "city": "Carrollton",
    "state": "TX",
    "lat": 32.771888,
    "lng": -96.647071
  },
  {
    "code": "470",
    "city": "Atlanta",
    "state": "GA",
    "lat": 33.770793,
    "lng": -84.43614
  },
  {
    "code": "475",
    "city": "Bridgeport",
    "state": "CT",
    "lat": 41.341175,
    "lng": -73.167001
  },
  {
    "code": "478",
    "city": "Macon",
    "state": "GA",
    "lat": 32.689186,
    "lng": -83.214208
  },
  {
    "code": "479",
    "city": "Fayetteville",
    "state": "AR",
    "lat": 35.523174,
    "lng": -93.859516
  },
  {
    "code": "480",
    "city": "Chandler",
    "state": "AZ",
    "lat": 33.486401,
    "lng": -111.758833
  },
  {
    "code": "484",
    "city": "Allentown",
    "state": "PA",
    "lat": 40.341781,
    "lng": -75.643876
  },
  {
    "code": "501",
    "city": "Little Rock",
    "state": "AR",
    "lat": 35.26111,
    "lng": -93.193786
  },
  {
    "code": "502",
    "city": "Louisville",
    "state": "KY",
    "lat": 38.215905,
    "lng": -85.235416
  },
  {
    "code": "503",
    "city": "Beaver",
    "state": "OR",
    "lat": 45.318736,
    "lng": -122.916239
  },
  {
    "code": "504",
    "city": "Kenner",
    "state": "LA",
    "lat": 29.865363,
    "lng": -89.655576
  },
  {
    "code": "505",
    "city": "Albuquerque",
    "state": "NM",
    "lat": 35.568629,
    "lng": -107.451999
  },
  {
    "code": "507",
    "city": "Austin",
    "state": "MN",
    "lat": 44.040521,
    "lng": -94.170011
  },
  {
    "code": "508",
    "city": "Cambridge",
    "state": "MA",
    "lat": 41.857075,
    "lng": -70.96184
  },
  {
    "code": "509",
    "city": "Kennewick",
    "state": "WA",
    "lat": 47.358864,
    "lng": -119.06016
  },
  {
    "code": "510",
    "city": "Alameda",
    "state": "CA",
    "lat": 37.737405,
    "lng": -122.08967
  },
  {
    "code": "512",
    "city": "Austin",
    "state": "TX",
    "lat": 30.471944,
    "lng": -97.726481
  },
  {
    "code": "513",
    "city": "Cincinnati",
    "state": "OH",
    "lat": 39.268072,
    "lng": -84.3669
  },
  {
    "code": "515",
    "city": "Ames",
    "state": "IA",
    "lat": 42.236267,
    "lng": -93.927577
  },
  {
    "code": "516",
    "city": "Freeport",
    "state": "NY",
    "lat": 40.750917,
    "lng": -73.398233
  },
  {
    "code": "517",
    "city": "Charlotte",
    "state": "MI",
    "lat": 42.275676,
    "lng": -84.503319
  },
  {
    "code": "518",
    "city": "Albany",
    "state": "NY",
    "lat": 43.562173,
    "lng": -73.985656
  },
  {
    "code": "520",
    "city": "Casas Adobes",
    "state": "AZ",
    "lat": 34.325295,
    "lng": -111.667117
  },
  {
    "code": "530",
    "city": "Chico",
    "state": "CA",
    "lat": 40.434209,
    "lng": -121.560896
  },
  {
    "code": "531",
    "city": "Omaha",
    "state": "NE",
    "lat": 41.252363,
    "lng": -95.997988
  },
  {
    "code": "534",
    "city": "Eau Claire",
    "state": "WI",
    "lat": 44.811349,
    "lng": -91.498494
  },
  {
    "code": "539",
    "city": "Bartlesville",
    "state": "OK",
    "lat": 36.7494864,
    "lng": -95.9782966
  },
  {
    "code": "540",
    "city": "Blacksburg",
    "state": "VA",
    "lat": 38.057324,
    "lng": -79.036418
  },
  {
    "code": "541",
    "city": "Bend",
    "state": "OR",
    "lat": 43.793004,
    "lng": -120.305909
  },
  {
    "code": "551",
    "city": "Bayonne",
    "state": "NJ",
    "lat": 40.925692,
    "lng": -74.073135
  },
  {
    "code": "557",
    "city": "St. Louis",
    "state": "MO",
    "lat": 38.627002,
    "lng": -90.199404
  },
  {
    "code": "559",
    "city": "Clovis",
    "state": "CA",
    "lat": 36.600669,
    "lng": -119.378031
  },
  {
    "code": "561",
    "city": "Boca Raton",
    "state": "FL",
    "lat": 26.640771,
    "lng": -80.448011
  },
  {
    "code": "562",
    "city": "Bellflower",
    "state": "CA",
    "lat": 33.88048,
    "lng": -118.093193
  },
  {
    "code": "563",
    "city": "Davenport",
    "state": "IA",
    "lat": 42.528086,
    "lng": -91.230288
  },
  {
    "code": "564",
    "city": "Seattle",
    "state": "WA",
    "lat": 47.606209,
    "lng": -122.33207
  },
  {
    "code": "567",
    "city": "Toledo",
    "state": "OH",
    "lat": 40.998598,
    "lng": -83.55333
  },
  {
    "code": "570",
    "city": "Scranton",
    "state": "PA",
    "lat": 41.340957,
    "lng": -76.360915
  },
  {
    "code": "571",
    "city": "Alexandria",
    "state": "VA",
    "lat": 38.837375,
    "lng": -77.397635
  },
  {
    "code": "573",
    "city": "Columbia",
    "state": "MO",
    "lat": 37.919598,
    "lng": -91.136288
  },
  {
    "code": "574",
    "city": "Elkhart",
    "state": "IN",
    "lat": 41.248048,
    "lng": -86.279023
  },
  {
    "code": "575",
    "city": "Alamogordo",
    "state": "NM",
    "lat": 34.116084,
    "lng": -105.750853
  },
  {
    "code": "580",
    "city": "Lawton",
    "state": "OK",
    "lat": 35.509837,
    "lng": -98.495317
  },
  {
    "code": "585",
    "city": "Arcade",
    "state": "NY",
    "lat": 42.757073,
    "lng": -77.977995
  },
  {
    "code": "586",
    "city": "Sterling Heights",
    "state": "MI",
    "lat": 42.707104,
    "lng": -82.901231
  },
  {
    "code": "601",
    "city": "Hattiesburg",
    "state": "MS",
    "lat": 31.765804,
    "lng": -89.761592
  },
  {
    "code": "602",
    "city": "Phoenix",
    "state": "AZ",
    "lat": 33.487025,
    "lng": -112.076198
  },
  {
    "code": "603",
    "city": "Dover",
    "state": "NH",
    "lat": 43.745418,
    "lng": -71.547951
  },
  {
    "code": "605",
    "city": "Rapid City",
    "state": "SD",
    "lat": 44.436144,
    "lng": -100.230488
  },
  {
    "code": "606",
    "city": "Ashland",
    "state": "KY",
    "lat": 37.540083,
    "lng": -83.597956
  },
  {
    "code": "607",
    "city": "Elmira",
    "state": "NY",
    "lat": 42.335268,
    "lng": -76.075461
  },
  {
    "code": "608",
    "city": "Janesville",
    "state": "WI",
    "lat": 43.376417,
    "lng": -90.232246
  },
  {
    "code": "609",
    "city": "Allentown",
    "state": "NJ",
    "lat": 39.784621,
    "lng": -74.657517
  },
  {
    "code": "610",
    "city": "Allentown",
    "state": "PA",
    "lat": 40.341781,
    "lng": -75.643876
  },
  {
    "code": "612",
    "city": "Minneapolis",
    "state": "MN",
    "lat": 44.929252,
    "lng": -93.25642
  },
  {
    "code": "614",
    "city": "Columbus",
    "state": "OH",
    "lat": 39.966582,
    "lng": -83.036841
  },
  {
    "code": "615",
    "city": "Murfreesboro",
    "state": "TN",
    "lat": 36.175352,
    "lng": -86.556462
  },
  {
    "code": "616",
    "city": "Grand Rapids",
    "state": "MI",
    "lat": 42.981195,
    "lng": -85.608166
  },
  {
    "code": "617",
    "city": "Boston",
    "state": "MA",
    "lat": 42.319045,
    "lng": -71.093525
  },
  {
    "code": "618",
    "city": "Alton",
    "state": "IL",
    "lat": 38.329447,
    "lng": -89.014305
  },
  {
    "code": "619",
    "city": "Chula Vista",
    "state": "CA",
    "lat": 32.745454,
    "lng": -116.727701
  },
  {
    "code": "620",
    "city": "Dodge City",
    "state": "KS",
    "lat": 37.767537,
    "lng": -98.48193
  },
  {
    "code": "623",
    "city": "Phoenix",
    "state": "AZ",
    "lat": 33.545877,
    "lng": -112.452827
  },
  {
    "code": "626",
    "city": "Alhambra",
    "state": "CA",
    "lat": 34.108144,
    "lng": -117.98469
  },
  {
    "code": "627",
    "city": "santa rosa",
    "state": "CA",
    "lat": 38.440429,
    "lng": -122.714054
  },
  {
    "code": "628",
    "city": "San Francisco",
    "state": "CA",
    "lat": 37.774929,
    "lng": -122.419415
  },
  {
    "code": "629",
    "city": "Brentwood",
    "state": "TN",
    "lat": 36.0325687,
    "lng": -86.7825235
  },
  {
    "code": "630",
    "city": "Naperville",
    "state": "IL",
    "lat": 41.810713,
    "lng": -88.254341
  },
  {
    "code": "631",
    "city": "Babylon",
    "state": "NY",
    "lat": 40.946958,
    "lng": -72.725587
  },
  {
    "code": "636",
    "city": "St. Charles",
    "state": "MO",
    "lat": 38.578392,
    "lng": -90.797942
  },
  {
    "code": "640",
    "city": "Allentown",
    "state": "NJ",
    "lat": 39.784621,
    "lng": -74.657517
  },
  {
    "code": "641",
    "city": "Mason City",
    "state": "IA",
    "lat": 41.800221,
    "lng": -93.234162
  },
  {
    "code": "646",
    "city": "New York City",
    "state": "NY",
    "lat": 40.781428,
    "lng": -73.965434
  },
  {
    "code": "650",
    "city": "Daly City",
    "state": "CA",
    "lat": 37.415331,
    "lng": -122.302585
  },
  {
    "code": "651",
    "city": "St. Paul",
    "state": "MN",
    "lat": 44.915292,
    "lng": -92.841185
  },
  {
    "code": "657",
    "city": "Anaheim",
    "state": "CA",
    "lat": 33.806316,
    "lng": -117.829679
  },
  {
    "code": "659",
    "city": "Birmingham",
    "state": "AL",
    "lat": 33.52066,
    "lng": -86.802489
  },
  {
    "code": "660",
    "city": "Marshall",
    "state": "MO",
    "lat": 39.647249,
    "lng": -93.383421
  },
  {
    "code": "661",
    "city": "Earlimart",
    "state": "CA",
    "lat": 35.075115,
    "lng": -118.902121
  },
  {
    "code": "662",
    "city": "Starkville",
    "state": "MS",
    "lat": 33.836267,
    "lng": -89.621696
  },
  {
    "code": "667",
    "city": "Baltimore",
    "state": "MD",
    "lat": 39.290384,
    "lng": -76.612189
  },
  {
    "code": "669",
    "city": "San Jose",
    "state": "CA",
    "lat": 37.338208,
    "lng": -121.886328
  },
  {
    "code": "670",
    "city": "saipan",
    "state": "MP",
    "lat": 15.177801,
    "lng": 145.750967
  },
  {
    "code": "671",
    "city": "Hagatna",
    "state": "GU",
    "lat": 13.44733,
    "lng": 144.767979
  },
  {
    "code": "678",
    "city": "Atlanta",
    "state": "GA",
    "lat": 33.770793,
    "lng": -84.43614
  },
  {
    "code": "679",
    "city": "Detroit",
    "state": "MI",
    "lat": 42.331427,
    "lng": -83.045753
  },
  {
    "code": "680",
    "city": "Auburn",
    "state": "NY",
    "lat": 42.9320202,
    "lng": -76.5672029
  },
  {
    "code": "681",
    "city": "Charleston",
    "state": "WV",
    "lat": 38.349819,
    "lng": -81.632623
  },
  {
    "code": "682",
    "city": "Arlington",
    "state": "TX",
    "lat": 32.655169,
    "lng": -97.488648
  },
  {
    "code": "684",
    "city": "Pago Pago",
    "state": "AS",
    "lat": -14.266062,
    "lng": -170.130305
  },
  {
    "code": "689",
    "city": "Orlando",
    "state": "FL",
    "lat": 28.538335,
    "lng": -81.379236
  },
  {
    "code": "701",
    "city": "Bismarck",
    "state": "ND",
    "lat": 47.446324,
    "lng": -100.469297
  },
  {
    "code": "702",
    "city": "Henderson",
    "state": "NV",
    "lat": 36.159086,
    "lng": -114.938366
  },
  {
    "code": "703",
    "city": "Alexandria",
    "state": "VA",
    "lat": 38.837375,
    "lng": -77.397635
  },
  {
    "code": "704",
    "city": "Charlotte",
    "state": "NC",
    "lat": 35.343951,
    "lng": -80.734736
  },
  {
    "code": "706",
    "city": "Athens",
    "state": "GA",
    "lat": 33.700602,
    "lng": -83.870619
  },
  {
    "code": "707",
    "city": "Benicia",
    "state": "CA",
    "lat": 39.887445,
    "lng": -123.19922
  },
  {
    "code": "708",
    "city": "Berwyn",
    "state": "IL",
    "lat": 41.559062,
    "lng": -87.748494
  },
  {
    "code": "712",
    "city": "Council Bluffs",
    "state": "IA",
    "lat": 42.23012,
    "lng": -95.418361
  },
  {
    "code": "713",
    "city": "Houston",
    "state": "TX",
    "lat": 29.837525,
    "lng": -95.377346
  },
  {
    "code": "714",
    "city": "Anaheim",
    "state": "CA",
    "lat": 33.806316,
    "lng": -117.829679
  },
  {
    "code": "715",
    "city": "Chippewa Falls",
    "state": "WI",
    "lat": 45.417223,
    "lng": -90.43033
  },
  {
    "code": "716",
    "city": "Cattaraugus",
    "state": "NY",
    "lat": 42.655359,
    "lng": -78.3959
  },
  {
    "code": "717",
    "city": "Lancaster",
    "state": "PA",
    "lat": 40.155116,
    "lng": -77.060091
  },
  {
    "code": "718",
    "city": "Bellerose",
    "state": "NY",
    "lat": 40.685997,
    "lng": -73.935788
  },
  {
    "code": "719",
    "city": "Alamosa",
    "state": "CO",
    "lat": 38.164629,
    "lng": -104.339161
  },
  {
    "code": "720",
    "city": "Boulder",
    "state": "CO",
    "lat": 39.713461,
    "lng": -104.82857
  },
  {
    "code": "724",
    "city": "New Castle",
    "state": "PA",
    "lat": 40.529223,
    "lng": -79.871479
  },
  {
    "code": "725",
    "city": "Henderson",
    "state": "NV",
    "lat": 36.0391456,
    "lng": -114.9819235
  },
  {
    "code": "726",
    "city": "San Antonio",
    "state": "TX",
    "lat": 29.4246002,
    "lng": -98.4951405
  },
  {
    "code": "727",
    "city": "Clearwater",
    "state": "FL",
    "lat": 28.028726,
    "lng": -82.692597
  },
  {
    "code": "730",
    "city": "Alton",
    "state": "IL",
    "lat": 38.890603,
    "lng": -90.184276
  },
  {
    "code": "731",
    "city": "Jackson",
    "state": "TN",
    "lat": 35.791081,
    "lng": -88.774074
  },
  {
    "code": "732",
    "city": "Brick Township",
    "state": "NJ",
    "lat": 40.260509,
    "lng": -74.294553
  },
  {
    "code": "734",
    "city": "Ann Arbor",
    "state": "MI",
    "lat": 42.146633,
    "lng": -83.671962
  },
  {
    "code": "737",
    "city": "Austin",
    "state": "TX",
    "lat": 30.267153,
    "lng": -97.74306
  },
  {
    "code": "740",
    "city": "Athens",
    "state": "OH",
    "lat": 39.68925,
    "lng": -82.238329
  },
  {
    "code": "743",
    "city": "Greensboro",
    "state": "NC",
    "lat": 36.0726355,
    "lng": -79.7919754
  },
  {
    "code": "747",
    "city": "Burbank",
    "state": "CA",
    "lat": 34.180839,
    "lng": -118.308966
  },
  {
    "code": "754",
    "city": "Coral Springs",
    "state": "FL",
    "lat": 26.150138,
    "lng": -80.486696
  },
  {
    "code": "757",
    "city": "Chesapeake",
    "state": "VA",
    "lat": 37.178366,
    "lng": -76.300123
  },
  {
    "code": "760",
    "city": "Apple Valley",
    "state": "CA",
    "lat": 35.077329,
    "lng": -116.569262
  },
  {
    "code": "762",
    "city": "Athens",
    "state": "GA",
    "lat": 33.700602,
    "lng": -83.870619
  },
  {
    "code": "763",
    "city": "Brooklyn Park",
    "state": "MN",
    "lat": 45.322976,
    "lng": -93.54338
  },
  {
    "code": "765",
    "city": "Kokomo",
    "state": "IN",
    "lat": 40.097063,
    "lng": -86.177642
  },
  {
    "code": "769",
    "city": "Hattiesburg",
    "state": "MS",
    "lat": 31.765804,
    "lng": -89.761592
  },
  {
    "code": "770",
    "city": "Atlanta",
    "state": "GA",
    "lat": 33.777593,
    "lng": -84.447258
  },
  {
    "code": "772",
    "city": "Port St. Lucie",
    "state": "FL",
    "lat": 27.310037,
    "lng": -80.462545
  },
  {
    "code": "773",
    "city": "Chicago",
    "state": "IL",
    "lat": 41.826251,
    "lng": -87.675835
  },
  {
    "code": "774",
    "city": "Brockton",
    "state": "MA",
    "lat": 41.857075,
    "lng": -70.96184
  },
  {
    "code": "775",
    "city": "Carson City",
    "state": "NV",
    "lat": 39.568474,
    "lng": -116.769254
  },
  {
    "code": "779",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.605203,
    "lng": -88.918992
  },
  {
    "code": "781",
    "city": "Lynn",
    "state": "MA",
    "lat": 42.255792,
    "lng": -70.993819
  },
  {
    "code": "785",
    "city": "Abilene",
    "state": "KS",
    "lat": 39.254088,
    "lng": -98.504536
  },
  {
    "code": "786",
    "city": "Hialeah",
    "state": "FL",
    "lat": 25.603078,
    "lng": -80.532102
  },
  {
    "code": "800",
    "city": "",
    "state": ""
  },
  {
    "code": "801",
    "city": "Ogden",
    "state": "UT",
    "lat": 40.617162,
    "lng": -111.805673
  },
  {
    "code": "802",
    "city": "Bennington",
    "state": "VT",
    "lat": 44.075223,
    "lng": -72.662746
  },
  {
    "code": "803",
    "city": "Columbia",
    "state": "SC",
    "lat": 33.894777,
    "lng": -81.061539
  },
  {
    "code": "804",
    "city": "Mechanicsville",
    "state": "VA",
    "lat": 37.425718,
    "lng": -77.980823
  },
  {
    "code": "805",
    "city": "Camarillo",
    "state": "CA",
    "lat": 34.953333,
    "lng": -120.148748
  },
  {
    "code": "806",
    "city": "Amarillo",
    "state": "TX",
    "lat": 34.662259,
    "lng": -101.598817
  },
  {
    "code": "808",
    "city": "Honolulu",
    "state": "HI",
    "lat": 20.663335,
    "lng": -157.330668
  },
  {
    "code": "810",
    "city": "Flint",
    "state": "MI",
    "lat": 42.982601,
    "lng": -83.195787
  },
  {
    "code": "812",
    "city": "Bloomington",
    "state": "IN",
    "lat": 38.738487,
    "lng": -86.516889
  },
  {
    "code": "813",
    "city": "Tampa",
    "state": "FL",
    "lat": 28.006915,
    "lng": -82.355531
  },
  {
    "code": "814",
    "city": "Erie",
    "state": "PA",
    "lat": 41.113357,
    "lng": -78.776102
  },
  {
    "code": "815",
    "city": "Joliet",
    "state": "IL",
    "lat": 41.605203,
    "lng": -88.918992
  },
  {
    "code": "816",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.305594,
    "lng": -94.409307
  },
  {
    "code": "817",
    "city": "Arlington",
    "state": "TX",
    "lat": 32.655169,
    "lng": -97.488648
  },
  {
    "code": "818",
    "city": "Agoura Hills",
    "state": "CA",
    "lat": 34.246629,
    "lng": -118.38236
  },
  {
    "code": "820",
    "city": "Camarillo",
    "state": "CA",
    "lat": 34.2164099,
    "lng": -119.0376573
  },
  {
    "code": "822",
    "city": "",
    "state": ""
  },
  {
    "code": "828",
    "city": "Asheville",
    "state": "NC",
    "lat": 35.565318,
    "lng": -82.543935
  },
  {
    "code": "830",
    "city": "Medina",
    "state": "TX",
    "lat": 29.405036,
    "lng": -99.279701
  },
  {
    "code": "831",
    "city": "Salinas",
    "state": "CA",
    "lat": 36.517724,
    "lng": -121.279329
  },
  {
    "code": "832",
    "city": "Baytown",
    "state": "TX",
    "lat": 29.837525,
    "lng": -95.377346
  },
  {
    "code": "833",
    "city": "",
    "state": ""
  },
  {
    "code": "838",
    "city": "Albany",
    "state": "NY",
    "lat": 42.6511674,
    "lng": -73.754968
  },
  {
    "code": "839",
    "city": "Columbia",
    "state": "SC",
    "lat": 34.0007493,
    "lng": -81.0343313
  },
  {
    "code": "843",
    "city": "Charleston",
    "state": "SC",
    "lat": 33.551999,
    "lng": -80.080251
  },
  {
    "code": "844",
    "city": "",
    "state": ""
  },
  {
    "code": "845",
    "city": "Kingston",
    "state": "NY",
    "lat": 41.68195,
    "lng": -74.259071
  },
  {
    "code": "847",
    "city": "Arlington Heights",
    "state": "IL",
    "lat": 42.195629,
    "lng": -88.103663
  },
  {
    "code": "848",
    "city": "Brick Township",
    "state": "NJ",
    "lat": 40.260509,
    "lng": -74.294553
  },
  {
    "code": "850",
    "city": "Pensacola",
    "state": "FL",
    "lat": 30.35353,
    "lng": -85.304696
  },
  {
    "code": "854",
    "city": "Charleston",
    "state": "SC",
    "lat": 32.7876012,
    "lng": -79.9402728
  },
  {
    "code": "855",
    "city": "",
    "state": ""
  },
  {
    "code": "856",
    "city": "Camden",
    "state": "NJ",
    "lat": 39.597545,
    "lng": -75.137975
  },
  {
    "code": "857",
    "city": "Boston",
    "state": "MA",
    "lat": 42.319045,
    "lng": -71.093525
  },
  {
    "code": "858",
    "city": "San Diego",
    "state": "CA",
    "lat": 32.930564,
    "lng": -117.134845
  },
  {
    "code": "859",
    "city": "Lexington",
    "state": "KY",
    "lat": 38.19049,
    "lng": -84.492289
  },
  {
    "code": "860",
    "city": "Bristol",
    "state": "CT",
    "lat": 41.684526,
    "lng": -72.617608
  },
  {
    "code": "862",
    "city": "Clifton",
    "state": "NJ",
    "lat": 41.006143,
    "lng": -74.52237
  },
  {
    "code": "863",
    "city": "Lakeland",
    "state": "FL",
    "lat": 27.325409,
    "lng": -81.391146
  },
  {
    "code": "864",
    "city": "Greenville",
    "state": "SC",
    "lat": 34.597028,
    "lng": -82.268514
  },
  {
    "code": "865",
    "city": "Knoxville",
    "state": "TN",
    "lat": 35.931336,
    "lng": -83.90434
  },
  {
    "code": "866",
    "city": "",
    "state": ""
  },
  {
    "code": "870",
    "city": "Jonesboro",
    "state": "AR",
    "lat": 34.729392,
    "lng": -92.083437
  },
  {
    "code": "872",
    "city": "Chicago",
    "state": "IL",
    "lat": 41.878113,
    "lng": -87.629798
  },
  {
    "code": "877",
    "city": "",
    "state": ""
  },
  {
    "code": "878",
    "city": "Pittsburgh",
    "state": "PA",
    "lat": 40.523255,
    "lng": -79.878626
  },
  {
    "code": "880",
    "city": "",
    "state": ""
  },
  {
    "code": "881",
    "city": "",
    "state": ""
  },
  {
    "code": "882",
    "city": "",
    "state": ""
  },
  {
    "code": "883",
    "city": "",
    "state": ""
  },
  {
    "code": "884",
    "city": "",
    "state": ""
  },
  {
    "code": "885",
    "city": "",
    "state": ""
  },
  {
    "code": "886",
    "city": "",
    "state": ""
  },
  {
    "code": "887",
    "city": "",
    "state": ""
  },
  {
    "code": "888",
    "city": "",
    "state": ""
  },
  {
    "code": "889",
    "city": "",
    "state": ""
  },
  {
    "code": "901",
    "city": "Memphis",
    "state": "TN",
    "lat": 35.264514,
    "lng": -89.686114
  },
  {
    "code": "903",
    "city": "Longview",
    "state": "TX",
    "lat": 32.705051,
    "lng": -95.389774
  },
  {
    "code": "904",
    "city": "Jacksonville",
    "state": "FL",
    "lat": 30.236743,
    "lng": -81.824942
  },
  {
    "code": "906",
    "city": "Sault Ste Marie",
    "state": "MI",
    "lat": 46.534917,
    "lng": -87.28168
  },
  {
    "code": "907",
    "city": "Anchorage",
    "state": "AK",
    "lat": 58.127197,
    "lng": -48.192896
  },
  {
    "code": "908",
    "city": "Washington Township",
    "state": "NJ",
    "lat": 40.69626,
    "lng": -74.815628
  },
  {
    "code": "909",
    "city": "Anaheim",
    "state": "CA",
    "lat": 34.10515,
    "lng": -117.298597
  },
  {
    "code": "910",
    "city": "Fayetteville",
    "state": "NC",
    "lat": 34.75927,
    "lng": -78.576525
  },
  {
    "code": "912",
    "city": "Savannah",
    "state": "GA",
    "lat": 31.668541,
    "lng": -82.04476
  },
  {
    "code": "913",
    "city": "Kansas City",
    "state": "KS",
    "lat": 38.895648,
    "lng": -94.985871
  },
  {
    "code": "914",
    "city": "Mount Vernon",
    "state": "NY",
    "lat": 41.155343,
    "lng": -73.749733
  },
  {
    "code": "915",
    "city": "El Paso",
    "state": "TX",
    "lat": 31.51532,
    "lng": -105.177627
  },
  {
    "code": "916",
    "city": "Elk Grove",
    "state": "CA",
    "lat": 38.575174,
    "lng": -121.35713
  },
  {
    "code": "917",
    "city": "New York City",
    "state": "NY",
    "lat": 40.685997,
    "lng": -73.935788
  },
  {
    "code": "918",
    "city": "Broken Arrow",
    "state": "OK",
    "lat": 35.820098,
    "lng": -95.585892
  },
  {
    "code": "919",
    "city": "Cary",
    "state": "NC",
    "lat": 35.763046,
    "lng": -78.665239
  },
  {
    "code": "920",
    "city": "Appleton",
    "state": "WI",
    "lat": 44.203386,
    "lng": -88.282572
  },
  {
    "code": "925",
    "city": "Antioch",
    "state": "CA",
    "lat": 37.831956,
    "lng": -121.839538
  },
  {
    "code": "928",
    "city": "Flagstaff",
    "state": "AZ",
    "lat": 34.795062,
    "lng": -111.803747
  },
  {
    "code": "929",
    "city": "Bellerose",
    "state": "NY",
    "lat": 40.724269,
    "lng": -73.7151313
  },
  {
    "code": "930",
    "city": "Bloomington",
    "state": "IN",
    "lat": 39.1670396,
    "lng": -86.5342881
  },
  {
    "code": "931",
    "city": "Clarksville",
    "state": "TN",
    "lat": 35.752962,
    "lng": -86.542593
  },
  {
    "code": "934",
    "city": "Babylon",
    "state": "NY",
    "lat": 40.74123595,
    "lng": -73.356691165361
  },
  {
    "code": "936",
    "city": "Huntsville",
    "state": "TX",
    "lat": 30.988685,
    "lng": -95.077769
  },
  {
    "code": "937",
    "city": "Dayton",
    "state": "OH",
    "lat": 39.737478,
    "lng": -83.943091
  },
  {
    "code": "938",
    "city": "Huntsville",
    "state": "AL",
    "lat": 34.730368,
    "lng": -86.586103
  },
  {
    "code": "940",
    "city": "Denton",
    "state": "TX",
    "lat": 33.567916,
    "lng": -98.775843
  },
  {
    "code": "941",
    "city": "Sarasota",
    "state": "FL",
    "lat": 26.49156,
    "lng": -81.666428
  },
  {
    "code": "947",
    "city": "Farmington Hills",
    "state": "MI",
    "lat": 42.644892,
    "lng": -83.401584
  },
  {
    "code": "949",
    "city": "Costa Mesa",
    "state": "CA",
    "lat": 33.583881,
    "lng": -117.662376
  },
  {
    "code": "951",
    "city": "Corona",
    "state": "CA",
    "lat": 33.725159,
    "lng": -117.067767
  },
  {
    "code": "952",
    "city": "Bloomington",
    "state": "MN",
    "lat": 44.748131,
    "lng": -93.595425
  },
  {
    "code": "954",
    "city": "Fort Lauderdale",
    "state": "FL",
    "lat": 26.150138,
    "lng": -80.486696
  },
  {
    "code": "956",
    "city": "Laredo",
    "state": "TX",
    "lat": 27.029143,
    "lng": -98.567131
  },
  {
    "code": "959",
    "city": "Hartford",
    "state": "CT",
    "lat": 41.684526,
    "lng": -72.617608
  },
  {
    "code": "970",
    "city": "Durango",
    "state": "CO",
    "lat": 39.516547,
    "lng": -106.512204
  },
  {
    "code": "971",
    "city": "Beaverton",
    "state": "OR",
    "lat": 45.196065,
    "lng": -122.70783
  },
  {
    "code": "972",
    "city": "Carrollton",
    "state": "TX",
    "lat": 32.771888,
    "lng": -96.647071
  },
  {
    "code": "973",
    "city": "Newark",
    "state": "NJ",
    "lat": 41.006143,
    "lng": -74.52237
  },
  {
    "code": "975",
    "city": "Kansas City",
    "state": "MO",
    "lat": 39.099726,
    "lng": -94.578566
  },
  {
    "code": "978",
    "city": "Haverhill",
    "state": "MA",
    "lat": 42.587448,
    "lng": -71.595462
  },
  {
    "code": "979",
    "city": "Bryan",
    "state": "TX",
    "lat": 29.834233,
    "lng": -96.309235
  },
  {
    "code": "980",
    "city": "Charlotte",
    "state": "NC",
    "lat": 35.343951,
    "lng": -80.734736
  },
  {
    "code": "984",
    "city": "Raleigh",
    "state": "NC",
    "lat": 35.779589,
    "lng": -78.638178
  },
  {
    "code": "985",
    "city": "Hammond",
    "state": "LA",
    "lat": 29.898815,
    "lng": -90.319067
  },
  {
    "code": "986",
    "city": "Boise",
    "state": "ID",
    "lat": 43.61656,
    "lng": -116.200835
  },
  {
    "code": "989",
    "city": "Alma",
    "state": "MI",
    "lat": 44.097502,
    "lng": -84.120784
  }
];

export const AREA_CODE_MAP: Record<string, AreaCodeInfo> = Object.fromEntries(
  AREA_CODES.map((info) => [info.code, info]),
);

export function lookupAreaCode(code: string): AreaCodeInfo | undefined {
  return AREA_CODE_MAP[code];
}
