#!/usr/bin/env node
/**
 * Regenerates the bundled datasets in `data/`:
 *   - data/dictionary.ts  (top-10k English words, 2-7 letters, + curated tech terms)
 *   - data/area-codes.ts  (NANP area code -> primary city/state)
 *
 * Usage: node scripts/generate-data.mjs
 *
 * Sources are public: first20hours/google-10000-english (public domain) and the
 * MIT-licensed node-areacodes dataset. Network access is required.
 */
import { writeFileSync } from "node:fs";

const WORDS_URL =
  "https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english.txt";
const AREA_CODES_URL =
  "https://raw.githubusercontent.com/BlueRival/node-areacodes/master/lib/data.json";

const TECH_TERMS = [
  "API", "CLI", "SSH", "SQL", "DNS", "TLS", "CDN", "GPU", "CPU", "RAM", "OS", "UX", "UI", "AI", "ML",
  "CODE", "LIVE", "LIFE", "LUCK", "DICE", "WIRE", "WALK", "TECH", "TOOL", "GROK", "GREP", "PIPE",
  "DATA", "CLOUD", "STACK", "CACHE", "QUEUE", "TOKEN", "PATCH", "MERGE", "SHELL", "CRON", "VIM",
  "BASH", "NODE", "REACT", "RUST", "JAVA", "LINUX", "MACOS", "DOCKER", "KUBERNETES", "DEBUG",
  "BYTES", "PIXEL", "RENDER", "SHADER", "ENGINE", "SERVER", "CLIENT", "DEPLOY", "BUILD", "COMMIT",
  "BRANCH", "REBASE", "PUSH", "PULL", "FORK", "REPO", "COMMAND", "SCRIPT", "HACK", "PWN", "PING",
  "PORT", "PROXY", "ROUTE", "HOST", "DOMAIN", "CERT", "KEY", "HASH", "SALT", "SEED", "NULL", "BOOL",
  "INT", "CHAR", "FLOAT", "ARRAY", "LIST", "MAP", "SET", "JSON", "YAML", "XML", "HTML", "CSS",
  "MKDIR", "CHMOD", "CHOWN", "SUDO", "KILL", "ECHO", "AWK", "SED", "CAT", "LESS", "MORE", "TAR",
  "ZIP", "CURL", "WGET", "SCP", "RSYNC", "GIT", "NPM", "PNPM", "YARN", "VITE", "NEXT", "VEGAS",
  "STRIP", "NEON", "CASINO", "POKER", "SLOTS", "JACKPOT", "BONUS", "GOLD", "LUCK", "ACE",
];

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return res.text();
}

function buildDictionary(source) {
  const seen = new Set();
  const words = [];
  for (const line of source.split(/\r?\n/)) {
    const word = line.trim().toLowerCase();
    if (!/^[a-z]+$/.test(word) || word.length < 2 || word.length > 7 || seen.has(word)) continue;
    seen.add(word);
    words.push(word.toUpperCase());
  }
  for (const raw of TECH_TERMS) {
    const word = raw.toUpperCase();
    if (word.length < 2 || word.length > 7 || seen.has(word)) continue;
    seen.add(word);
    words.push(word);
  }

  const rank = {};
  words.forEach((word, index) => {
    rank[word] = index;
  });

  const banner = `// GENERATED by scripts/generate-data.mjs — do not edit by hand.
// Source: first20hours/google-10000-english (public domain), in frequency order,
// filtered to 2-7 letters, plus a hand-curated list of dev/tech and Las Vegas
// terms appended at the end. Lower rank = more common.
`;
  return `${banner}
export const DICTIONARY: readonly string[] = ${JSON.stringify(words)};

/** Word -> frequency rank. Words outside the list are treated as rare. */
export const DICTIONARY_RANK: Record<string, number> = ${JSON.stringify(rank)};
`;
}

function buildAreaCodes(source) {
  const data = JSON.parse(source);
  const entries = Object.keys(data)
    .sort()
    .map((code) => {
      const entry = data[code];
      const location = entry.location ?? {};
      return {
        code,
        city: entry.city || "",
        state: entry.stateCode || "",
        ...(typeof location.latitude === "number" && typeof location.longitude === "number"
          ? { lat: location.latitude, lng: location.longitude }
          : {}),
      };
    });

  const banner = `// GENERATED by scripts/generate-data.mjs — do not edit by hand.
// Source: node-areacodes data.json (MIT). NANP area code -> primary city/state
// plus a representative coordinate used for "use my location".
export interface AreaCodeInfo {
  code: string;
  city: string;
  state: string;
  lat?: number;
  lng?: number;
}
`;
  return `${banner}
export const AREA_CODES: readonly AreaCodeInfo[] = ${JSON.stringify(entries, null, 2)};

export const AREA_CODE_MAP: Record<string, AreaCodeInfo> = Object.fromEntries(
  AREA_CODES.map((info) => [info.code, info]),
);

export function lookupAreaCode(code: string): AreaCodeInfo | undefined {
  return AREA_CODE_MAP[code];
}
`;
}

const [wordsSource, areaCodesSource] = await Promise.all([
  fetchText(WORDS_URL),
  fetchText(AREA_CODES_URL),
]);

writeFileSync(new URL("../data/dictionary.ts", import.meta.url), buildDictionary(wordsSource));
writeFileSync(new URL("../data/area-codes.ts", import.meta.url), buildAreaCodes(areaCodesSource));
console.log("Regenerated data/dictionary.ts and data/area-codes.ts");
